### ISSUE TITLE
Is it possible to swipe down on the modal panel to close it?

### ISSUE THREAD

**Issue by GroovinChip** [RaviKavaiya/sliding_panel#10]
After opening a modal panel, I'm only able to close it by pressing the back button. Like a regular modalBottomSheet, I expect to be able to swipe it closed as well as by using the back button. Is this possible? I saw nothing in the docs for it.

Code:
```
  /// Show bottom panel
  void showPanel() async {
    final panel = await showModalSlidingPanel(
      context: context,
      panel: (context) => SlidingPanel(
        panelController: _panelController,
        snapping: PanelSnapping.enabled,
        isDraggable: true,
        backPressBehavior: BackPressBehavior.POP,
        isTwoStatePanel: true,
        size: PanelSize(
          closedHeight: 0.5,
          expandedHeight: 1.0,
        ),
        backdropConfig: BackdropConfig(
          enabled: true,
          dragFromBody: true,
        ),
        content: PanelContent(
          headerWidget: PanelHeaderWidget(
            decoration: PanelDecoration(
              backgroundColor: Colors.grey[800]
            ),
            options: PanelHeaderOptions(
              primary: false,
            ),
            headerContent: Padding(
              padding: const EdgeInsets.all(6),
              child: Material(
                elevation: 4,
                child: TextField(
                  onTap: () => _panelController.expand(),
                  decoration: InputDecoration(
                    filled: true,
                    fillColor: Theme.of(context).canvasColor,
                    border: InputBorder.none,
                    prefixIcon: Icon(Icons.search, color: Colors.white),
                    suffixIcon: Icon(Icons.more_vert, color: Colors.white),
                    hintText: 'Instance Search...'
                  ),
                ),
              ),
            ),
          ),
          panelContent: [
            ...
          ],
        ),
      ),
    );
  }
```
Screenshot:
![image](https://user-images.githubusercontent.com/4250470/77498051-1f86e180-6e25-11ea-95a9-3ee1a1a0c310.png)

**Comment by RaviKavaiya** [comment]
@GroovinChip For this to work, you can follow below steps (These are similar to Solution - 1 provided in #8):
What you have done is, you have created a panel having only two states. Moreover, you set `closedHeight` to 0.5. That means, the panel can not go below 0.5 position. (You are able to close by pressing back, as you set `BackPressBehavior.POP`, that is desired behaviour of the panel)

- You can set `closedHeight` to `0.0` and you will be able to close the panel with swipe gesture. But with this, you will only be able to close and expand the panel (No in-between state as in your screenshot). 

- Otherwise, you can set `isTwoStatePanel` to `false` and provide `collapsedHeight` to `size` parameter. (Also provide `closedHeight` to `0.0`). That way, you will be able to close, collapse and expand the panel.

Let me know whether this solved your issue...

**Comment by GroovinChip** [comment]
Got it! Thank you so much
