### ISSUE TITLE
Is it possible to get the PanelHeaderWidget to avoid the status bar when fully expanded? 

### ISSUE THREAD

**Issue by GroovinChip** [RaviKavaiya/sliding_panel#11]
![Screenshot of current behavior: ](https://i.imgur.com/Ia34NQi.png)

The code is the same as in my other issues (I'm filing this on mobile)

**Comment by RaviKavaiya** [comment]
Set primary to true in PanelHeaderOptions for this

**Comment by GroovinChip** [comment]
That did the trick, thank you!

**Comment by GroovinChip** [comment]
Actually, this results in a weird morphing of the widget. There is an extra area above the textfield

![Screenshot](https://i.imgur.com/xCXz0G5.png)

**Comment by RaviKavaiya** [comment]
That's what you asked...
You wanted to ignore status bar.

**Comment by GroovinChip** [comment]
Yes, that is true, but it would be nice to have this ability without it being at the expense of the UI itself. Is it possible to have the header simply stop at the status bar instead of going under it?

**Comment by RaviKavaiya** [comment]
Ok, now I understood it clearly...

Actually, I encountered this problem before. I also implemented the solution you are wanting in one of my previous versions.
The trick was:

- In `panel.dart` file, inside the `build()` method, wrap everything with `SafeArea()` (This is the recommended solution for your issue, wrap the `WillPopScope` with `SafeArea`). This seemed to be working for me. But, there are 2 problems with this approach:
1. Not everyone would like this. Somebody would like to have a full-screen panel.
2. There would be difference in the panel's colour and status bar colour. This would not look good. (This can also worked on, but you know...)

For this purposes, I gave up on this `SafeArea` approach.

---

### Another solution (Not recommended, just a workaround if you don't want to modify the `panel.dart`):

- Instead of giving static `expandedHeight` as `1.0`, create a `double` called `expSize`, for example and use that.

- Then create `didChangeDependencies` as below:

```
@override
  void didChangeDependencies() {
    super.didChangeDependencies();

    double topPadding = MediaQuery.of(context).padding.top;
    double screenHeight = MediaQuery.of(context).size.height;

    setState(() {
      expSize = (1.0 - (topPadding / screenHeight));
    });
  }

```

- And, you are done. Your panel would not go below the status bar.

#### Again, I would not recommend this approach. For your usage, I would only recommend the first solution (Wrap with `SafeArea`).

**Comment by GroovinChip** [comment]
The second approach actually works well for me. Thank you so much!
