### ISSUE TITLE
Back btn close parent

### ISSUE THREAD

**Issue by ghost** [RaviKavaiya/sliding_panel#13]
Hi,
Thanks for a lot of grate work!
One think which is blocker for me to use your lib is behaviour of back btn. It close not only panel but also page which launch it. 
You can see this behaviour in your 'Modal panel' example.
Steps:
1 ) Open Modal Panel Page
2) Press Open the panel btn
3) press Android back btn.
Expected behaviour: Panel should close
Actual behaviour: Panel is close as well as 'Modal Panel' Page

**Comment by RaviKavaiya** [comment]
*[Apply below solutions after updating package to latest version `1.0.4` uploaded today, that contains some bug fixes]*

@hammer814  Thanks for opening the issue. For your issue, a proper `BackPressBehavior` is needed. (Please read the docs of it, before directly jumping to the solution)

It works as expected. The `Modal Panel` example page will only be popped (closed) if you press back button twice (First press -> close panel, Second -> close page).

There are some things that affect the behavior of popping the panel (and its containing route).

For modal panels, if, at any time, the height is found to be `0.0`, the route is popped (Means, the panel is popped and again pressing the back button will even close the main page).

This is kept intentionally. Imagine a situation when panel is fully closed (at 0.0 position) and you are not able to interact with the app. So, for that purposes, when you actually move panel to 0.0 position (read again, not only close the panel, talking about position) the ROUTE IS POPPED. (This is for modal panels only, normal panels aren't affected by this behavior).

### Solutions to your problem:

1. **(RECOMMENDED)** As in the modal panel example, we have used `headerSizeIsClosed: true`, the `closedHeight` of panel will be > 0.0. So, simply provide any `persisting` behavior. Like, `BackPressBehavior.PERSIST` or `BackPressBehavior.CLOSE_PERSIST`. This way, the panel will BE closed, but the example page won't. **Remember,** that this will work ONLY because the closedHeight will be > 0.0. If you set `headerSizeIsClosed: false`, the closedHeight will stay 0.0 (as given in `size` parameter) and no matter what `backPressBehavior` you have given, the route *will pop.*

2. **(NOT RECOMMENDED)** However, if you want the panel to HAVE 0.0 height and STILL NOT pop the route, you can do the same steps in the two-state panels. Set closedHeight to 0.0 and set `backPressBehavior: BackPressBehavior.CLOSE_PERSIST`. That way, the panel will close, but the page will *not* be popped.

**Comment by samuelmukoti** [comment]
Hi,

I'm using the sliding_panel with a controller and was attempting to use the controller to close the panel when clicked.  I get a method called on null error when the close button is tapped.  Do you have an example or best practice of how someone can close the panel programmatically rather than dragging it closed?

**Comment by RaviKavaiya** [comment]
@samuelmukoti It works as expected. Look for Two state panel example in example directory. 
Let me know how it goes

**Comment by omidraha** [comment]
When we are not in `modal` mode:
```dart
SlidingPanel(
  panelController: pc,
  content: PanelContent(
    headerWidget: PanelHeaderWidget(
      headerContent: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Text(
        'This is a SlidingPanel',
        style: Theme.of(context).textTheme.title,
        ),
      ),
      options: PanelHeaderOptions(centerTitle: true),
    ),
	
    // The only REQUIRED parameter
    panelContent: List.generate(20, (i) {
      return ListTile(
        title: Text('Item : ${i + 1}'),
      );
    }).toList(),

    bodyContent: Center(
      child: RaisedButton(
        onPressed: () {
        pc.collapse();
        },
        child: Text('Open the panel'),
      ),
    ),
  ),
  size: PanelSize(closedHeight: 0.0),
  // apply snapping effect
  snapping: PanelSnapping.enabled,
),
```
It's possible the `back` keyboard button only close the `panelContent` ?

**Comment by RaviKavaiya** [comment]
Hi @omidraha :wave: 
Keep backpressbehavior to `CLOSE_PERSIST` and set `closedHeight` to anything greater than 0.0 (or use `headerSizeIsClosed`)

Let me know if it helps...

**Comment by omidraha** [comment]
Hi,
Actually. in normal behavior it works,
But because I have a `WillPopScope`  on the parent widget, It does [not](https://github.com/flutter/flutter/issues/47088) work.
Unless it is in the PopupRoute (`Modal` mode) .

**Comment by RaviKavaiya** [comment]
But why do you want nested `WillPopScope`? You can change `BackPressBehavior` at any time (setState). It will work the way you want. There are many possibilities.

Try it. 😄 

**EDIT:** The point you have mentioned is also understandable. But until that happens, you can use setState on `backPressBehavior`. Let me know if any of `BackPressBehavior` is missing. (FYI, please also have a look at `PanelPoppingBehavior`)

**Comment by omidraha** [comment]
This is because parts of the page, including the header (back navigator) and footer (next navigator), are controlled by another parent widget. and this parent widget already have `WillPopScope`. 
Hence the  `WillPopScope` [defined](https://github.com/RaviKavaiya/sliding_panel/blob/master/lib/src/panel.dart#L1143) in the `sliding_panel` is [not](https://github.com/flutter/flutter/issues/47088) available at all.

**Comment by RaviKavaiya** [comment]
@omidraha I agree on above issue. Unfortunately, I can do nothing related to this

**Comment by omidraha** [comment]
One solution for me to solve this issue, is to use `sliding panel` in `modal` mode,
But while I use `modal` mode, I have another issue:
The `ListView` inside modal is not rebuild. (Here is  [issue](https://github.com/felangel/bloc/issues/1594))
I don't know this issue is related to `sliding panel` package or `bloc` package.

**Comment by RaviKavaiya** [comment]
Hello @omidraha I am not sure whether you would be able to do that. Please try the suggestion you got from the issue created in bloc.

If that doesn't work, I will surely take a look at this...

**Comment by RaviKavaiya** [comment]
@omidraha Check out the Pull Request I made.

**Comment by omidraha** [comment]
Thanks, 
[Fixed](https://github.com/omidraha/sample_modal/pull/1) with your pull request.

**Comment by omidraha** [comment]
Is there a way to update [options](https://github.com/omidraha/sample_modal/blob/master/lib/pages/home/screen/home.dart#L87) and [decoration](https://github.com/omidraha/sample_modal/blob/master/lib/pages/home/screen/home.dart#L104) of `headerWidget` with `BlocBuilder` ?
Because for wrapping them,  return type of  BlocBuilder is `Wdiget` and is not related to  `options` and `decoration`.

**Comment by RaviKavaiya** [comment]
Nope. You can't.

**Comment by RaviKavaiya** [comment]
@omidraha If you have any other doubts from now on, I would suggest that you create a separate issue...

Thanks.
