### ISSUE TITLE
useSafeArea Does not work as expected

### ISSUE THREAD

**Issue by ErliSoares** [RaviKavaiya/sliding_panel#14]
If I disable the property below, stay with the padding, as shown in the image below:
https://github.com/RaviKavaiya/sliding_panel/blob/f51a1be69f48c8e4b8dcabc67a12a74034ec790c/lib/src/panel_widget.dart#L268

![image](https://user-images.githubusercontent.com/2334509/79083212-31142880-7d03-11ea-8e7e-e557ba49a2a7.png)

However, if you enable the property, the top bar of the app is changed, not making it transparent as shown in the image below

![image](https://user-images.githubusercontent.com/2334509/79083197-1b9efe80-7d03-11ea-9fb0-c30fa4f0376c.png)

I wanted to put both options, without the padding since the modal will not reach 100% of the screen and allow it to be transparent, is that possible? I made a copy of the project and removed the padding, but I would like to use the library if possible

Thank you very good library, and sorry for the english, it's not very good

**Comment by RaviKavaiya** [comment]
@ErliSoares Thanks for opening the issue.
This is now fixed in `v1.0.5` :tada:

Follow below steps to solve your issue:
- Set `useSafeArea: true`.
- In `headerWidget`'s `options`, set `primary: false`.

That way, you background content will stay as it is (fullscreen) and panel will avoid intrusions like status bar and notch.

Kindly, update the package and try above solution. You can close the issue if your problem is solved.

### EDIT: As of version `1.1.1`, the parameter `useSafeArea` is renamed to `safeAreaConfig`.

**Comment by ErliSoares** [comment]
It worked perfectly for me, thanks
