### ISSUE TITLE
question: setting up the different panel heights in pixel

### ISSUE THREAD

**Issue by 32mandev** [RaviKavaiya/sliding_panel#17]
Hello,
thank you for this nice work!

Is it possible to setup some panel heights in pixels and not as a percentage of the screen's height?
(I mostly need to set the closed panel height in pixels).

**Comment by RaviKavaiya** [comment]
Hi @32mandev Unfortunately, this has not been implemented. Because, if we want to target multiple device sizes, setting panel size in pixels won't help you much.

But, you can do this yourself (I haven't checked, but please try and tell me):

```dart

initState() {}

// ...

const double heightInPixels = 64.0; // <- Your desired height
double closedHeight = 0.0;

// ...

void didChangeDependencies() { /* So, it will work if you change device orientation */
  super.didChangeDependencies();

  double screenHeight = MediaQuery.of(context).size.height;

  setState(() {
    closedHeight = (heightInPixels / screenHeight);
  }); 
}

Widget build(BuildContext context) { // <- Your build method
  // ...
  SlidingPanel(
    size: PanelSize(
      closedHeight: closedHeight,
    ),
  );
  // ...
}

```

Again, I would not recommend this approach as this will not work properly on different devices.

Let me know if you have any other query...

**Comment by 32mandev** [comment]
Thank you!
