### ISSUE TITLE
Nested ternary operators make code completely unreadable. 

### ISSUE THREAD

**Issue by Makarezp** [RaviKavaiya/sliding_panel#3]
Deep nesting of ternary operators make very difficult to read the code. 
Also I would think about somehow separating autosizing code from the rest.

**Comment by RaviKavaiya** [comment]
First of all, thanks for your help in refactoring the code.

> I would think about somehow separating autosizing code from the rest.

The AutoSizing code is divided only in 2 functions (around 150 lines). And called around 4 times, each.

Currently I have no intention to do that. Because, these functions are very closely related to the PanelState class (private members). Separating them would require passing a lot of parameters. Moreover, it uses ```setState()``` multiple times.

Yes, we can somehow manage by returning the values we use in ```setState()``` , but you know what I mean. So separating them would simply **increase** the complexity.

---

> Deep nesting of ternary operators make very difficult to read the code.

Ok, nice suggestion. 

If you used older releases, I have separated a couple of things from the build() function.
But as you figured out, I still feel a little discomfort while managing the code in ```build()``` function. That surely needs to be done in a near future release I am working on right now. Basically, I will create separate functions for the same to increase readability.

Let me know if you agree with my decision. :+1:


This issue will be closed after some refactoring is done.

**Comment by RaviKavaiya** [comment]
@alvinvin00 you referenced an issue that is not related to this issue.

I request you not to reference issues irrelevant to current issue.

**Comment by alvinvin00** [comment]
> @alvinvin00 you referenced an issue that is not related to this issue.
> 
> I request you not to reference issues irrelevant to current issue.

Sorry, I clicked New Issue on wrong place :(

**Comment by RaviKavaiya** [comment]
Fixed in v1.0.1
