### ISSUE TITLE
Snap panel is not work when velocity is 0.0

### ISSUE THREAD

**Issue by sososdk** [RaviKavaiya/sliding_panel#5]
Set `snapPanel` to `true`, But it is not work when velocity is 0.0.

**Comment by RaviKavaiya** [comment]
But when velocity is 0.0?

**Comment by RaviKavaiya** [comment]
I guess your issue is related to this:

[https://github.com/RaviKavaiya/sliding_panel/blob/master/lib/src/panel_widget.dart#L71](https://github.com/RaviKavaiya/sliding_panel/blob/master/lib/src/panel_widget.dart#L71)

**Comment by sososdk** [comment]
@RaviKavaiya Sorry! I mean this `velocity `

https://github.com/RaviKavaiya/sliding_panel/blob/2b71951ad6f8b0b7ffd566b316fd578a2e5ca797/lib/src/scrolling.dart#L66

**Comment by RaviKavaiya** [comment]
@sososdk thanks.
I also had the same confusion when developing this package.
Actually, this code is brought from ```DraggableScrollableSheet()```. It is the way this scroll controller works.

You can see that below that line, we have ```super.goBallistic()```, which tells the panel that the INTERNAL content should scroll. If we don't do that, our content wouldn't scroll.

EDIT: this is the case when panel has been stopped dragging, and the panel should start scrolling the content.

I hope I could help you. If you are satisfied with the answer, you can close this issue. Otherwise comment.
