### ISSUE TITLE
snapPanel only works sometimes

### ISSUE THREAD

**Issue by fremfi** [RaviKavaiya/sliding_panel#6]
Is there a way to always make the panel snap to closed, collapsed, and expanded states? i want the slightest drag, for the panel to snap in the direction of the drag. currently with snapPanel set to true, its only snapping to expanded when i do a quick drag. I'm using a simulator btw.

**Comment by RaviKavaiya** [comment]
> I'm using a simulator btw.

This doesn't affect the functionality. Works in similar manner as a physical device. (I guess)

---

It is already as you want. It depends on how much size you have specified to each `PanelState`. (Also `isTwoStatePanel` must be false.) AND your dragging of the panel.

While dragging, whenever you leave your finger from the panel, the code will check the actual position of the panel and work accordingly.

EXAMPLE:
Consider the `PanelSize` as below:
closed: 0.2, collapsed: 0.4, expanded: 0.9

Now, suppose that panel is currently `closed`. You start dragging and you stop at position: 0.7.
So, the panel will snap to `expanded`. Because, the user wants to `expand` the panel.
However, If you stop dragging at 0.3 the panel will `collapse`, NOT `expand`. Because, the user actually wants to open half panel, not fully.

You can check the code that decides what to do when user snaps the panel [HERE](https://github.com/RaviKavaiya/sliding_panel/blob/master/lib/src/utils.dart#L70)

---

> snapping to expanded when i do a quick drag

Maybe when you 'quick drag' you release your finger after the panel has *crossed* the collapsed state size. That's why its always expanding.


If you think that this is not the answer you want (Or I mis-understood your query), then please elaborate more.

If you are satisfied with my answer, then you can close this issue.

Thanks.

**Comment by fremfi** [comment]
Hey, It works as you say when i swipe, but when i click and drag up or down, the panel stops wherever i stop, it doesnt continue the motion

**Comment by RaviKavaiya** [comment]
I did not understand. Click and drag up or down? Can you please elaborate?

**Comment by fremfi** [comment]
When i swipe(quick drag gesture), the panel snaps but when I press the panel, and drag it slowly and release, it stops wherever i stop and doesn't snap to the nearest expanded or collapsed state.

**Comment by RaviKavaiya** [comment]
@fremfi all the actions, tapping, swiping, snapping take precedence over each other. (They cancel previous event).

For more info. about not snapping, I would suggest you to see [This](https://github.com/RaviKavaiya/sliding_panel/blob/master/lib/src/panel_widget.dart#L81)
